In [ ]:
import numpy as np
import re
from io import StringIO

class Machine():
    def __init__(self):    
        self.lights = []
        self.buttons = []
        self.yoltages = []

    def __repr__(self):
        return f"L: {self.lights} \nB: {np.array(self.buttons)} \nY: {self.yoltages} \n ---------------"
    
pattern = re.compile(r"^\[([.#]+)\]\s*((?:\([^()]+\)\s*)+)\{([^}]+)\}$")
pattern_buttons = re.compile(r"\(([^()]+)\)")
pattern_digits = re.compile(r"\d+")

with open("10/input.txt") as inpt:
    machines = []
    for line in inpt.readlines():
        match = pattern.match(line.strip()).groups()
        machine = Machine()
        
        # [0 if ch == "." else 1 for ch in match[0]]
        machine.lights = np.fromiter(((ch == "#") for ch in match[0]), int)
        for but in pattern_buttons.findall(match[1].strip()):
            arr = np.zeros(len(match[0]), dtype=int)
            arr[np.fromiter((int(n) for n in pattern_digits.findall(but)), int)] = 1
            machine.buttons.append(arr)
        
        machine.yoltages = np.fromiter((int(n) for n in pattern_digits.findall(match[2])), int)
        print(machine)
        
a = np.array(([0, 1, 0, 1], [0, 0, 1, 1]))

np.bitwise_xor(a, a)

[0 1 1 0] 
 [[0 0 0 1]
 [0 1 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [1 0 1 0]
 [1 1 0 0]] 
 [3 5 4 7] 
 ---------------
[0 0 0 1 0] 
 [[1 0 1 1 1]
 [0 0 1 1 0]
 [1 0 0 0 1]
 [1 1 1 0 0]
 [0 1 1 1 1]] 
 [ 7  5 12  7  2] 
 ---------------
[0 1 1 1 0 1] 
 [[1 1 1 1 1 0]
 [1 0 0 1 1 0]
 [1 1 1 0 1 1]
 [0 1 1 0 0 0]] 
 [10 11 11  5 10  5] 
 ---------------


array([[0, 0, 0, 0],
       [0, 0, 0, 0]])